server/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'blogs#index'
  resources :blogs
  get "/about", to: "static_page#about"
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

server/app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

server/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :blogs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

server/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update, :destroy]

    def index
        @blogs = Blog.all()
    end

    def new
    end

    def create
        #@blog = Blog.new(blog_params)
        #@blog.user = current_user
        @blog = current_user.blogs.new(blog_params)
        #render plain: @blog.inspect
        #return 
        if (@blog.save!)
            redirect_to root_path
        else
            render plain: @blog.inspect
        end
    end

    def edit
        @newBlog = Blog.find(params[:id])
        if @newBlog.user.id != current_user.id
            redirect_to root_path
            return
        end
    end

    def update
        #render plain: params[:post].inspect
        #return 
        @newBlog = Blog.find(params[:id])
        if @newBlog.user.id != current_user.id
            redirect_to root_path
            return
        end
        if (@newBlog.update(blog_params))
            redirect_to @newBlog   
        else
            render "edit"
        end
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def destroy
        @blog = Blog.find(params[:id])
        if @blog.user.id != current_user.id
            redirect_to root_path
            return
        end
        @blog.destroy
        redirect_to root_path
    end

    private def blog_params
        params.require(:newBlog).permit(:title, :content)
    end

end

server/app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
    before_action :authenticate_user!, only: [:about]
    def home
    end

    def about
    end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/blogs_helper.rb
module BlogsHelper
end

server/app/helpers/static_page_helper.rb
module StaticPageHelper
end

server/app/views/blogs/edit.html.erb
<h1>Edit</h1>
<%= form_for :newBlog, url:blog_path(@newBlog), method: :patch do |f| %>
    <p>
        <%= f.label :title%>
        <%= f.text_field(:title, {:class => "form-control"}) %>
    </p>
    <p>
        <%= f.label :content%>
        <%= f.text_area(:content , {:class => "form-control"}) %>
    </p>
    <p>
        <%= f.submit(:class => "btn btn-success")%>
    </p>
<% end %>

server/app/views/blogs/index.html.erb
<h1>All Blogs</h1>
<%= @blogs.each do |blog| %>
    <div class="well">
        <h3> <%= blog.title %> </h3>
        <p> <%= blog.content %> </p>
        <p> <%= blog.user.email %> </p>
        <%= link_to 'Show', blog_path(blog), :class => "btn btn-success " %>
        <%= link_to 'Edit', edit_blog_path(blog), :class => "btn btn-primary",  method: :get %>
        <%= link_to 'Delete', blog_path(blog), :class => "btn btn-danger", method: :Delete %>
        <hr>
    </div>
<% end %>

server/app/views/blogs/new.html.erb
<h1>Add blog here</h1>
<%= form_for :newBlog, url:blogs_path, method: :post do |f| %>
    <p>
        <%= f.label :title%>
        <%= f.text_field(:title, {:class => "form-control"}) %>
    </p>
    <p>
        <%= f.label :content%>
        <%= f.text_area(:content , {:class => "form-control"}) %>
    </p>
    <p>
        <%= f.submit(:class => "btn btn-success")%>
    </p>
<% end %>

server/app/views/blogs/show.html.erb
<h3> <%= @blog.title %> </h3>
<p> <%= @blog.content %> </p>
<p> <%= @blog.user.email %> </p>
<%= link_to 'Edit', edit_blog_path(@blog), :class => "btn btn-primary",  method: :get %>
<%= link_to 'Delete', blog_path(@blog), :class => "btn btn-danger", method: :Delete %>

server/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Rails Blog Authenticated</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, method: :get, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, method: :get, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Blogs", blogs_path, method: :get, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Blog", new_blog_path, method: :get, :class => "nav-link" %>
      </li>
    </ul>
    <ul>
      <li class="nav-item dropdown">
        <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit", edit_user_registration_path, method: :get, :class => "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {confirm: "Log Out?"}, :class => "dropdown-item" %>
          </div>
        <% else %>
          <span> <%= link_to 'LOG IN', new_user_session_path, method: :get, :class => "btn btn-success" %> </span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Server</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

server/app/views/static_page/about.html.erb
This is AboutPage

server/app/views/static_page/home.html.erb
This is HomePage

<% if user_signed_in? %>
    <p> Current User: <%= current_user.email %></p>
    <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, data: {confirm: "Log Out?"}, :class => "btn btn-danger" %>
<% else %>
    <%= link_to 'LOG IN', new_user_session_path, method: :get, :class => "btn btn-success" %>
<% end %>